In [1]:
import numpy as np

In [2]:
fruits = np.array(["kiwi", "mango", "strawberry"])
mask = np.array([False, False, True])

In [3]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [4]:
mask = a == 0
a[mask]

array([0, 0, 0])

In [5]:
a != 12

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [6]:
# How many negative numbers are there?
a < 0 # vectorized comparison operation
sum(a < 0) # sum all the booleans 
(a < 0).sum()

negatives = a[a < 0]
negatives
len(negatives)

4

In [7]:
a[a < 0]

array([-2, -1, -6, -7])

In [8]:
# How many positive numbers are there?
positives = a[a > 0] # index syntax is super important
len(positives)

5

In [9]:
# How many even positive numbers are there?
is_positive_mask = a > 0
positives = a[is_positive_mask]

is_even_mask = positives % 2 == 0
positive_evens = positives[is_even_mask]
positive_evens


array([ 4, 10, 12])

In [10]:
# Elementwise "&" operator to merge two masks
positives = a > 0
evens = a % 2 == 0
positives & evens
a[positives & evens]

array([ 4, 10, 12])

In [11]:
# Another approach with .intersect1d
positives_in_a = a[a > 0]
evens_in_a = a[a % 2 == 0]
len(np.intersect1d(positives_in_a, evens_in_a))

3

In [12]:
# Using a .logical_and method from numpy
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
even_and_positive = np.logical_and(a > 0, a % 2 == 0)
a[even_and_positive]

array([ 4, 10, 12])

In [13]:
# # Whittling down the original value
# a = a[a > 0]
# a = a[a % 2 == 0]
# a

In [14]:
# If you were to add 3 to each data point, how many positive numbers would there be?
add_three = a + 3
len(add_three[add_three > 0])

10

In [15]:
# If you squared each number, what would the new mean and standard deviation be?
squares = a**2

print("Mean", squares.mean())
print("Standard deviation", squares.std())

Mean 74.0
Standard deviation 144.0243035046516


In [16]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the center of the data is at 0. 
# This is done by subtracting the mean from each data point. Center the data set.
centered = a - a.mean()
centered

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [17]:
# Calculate the z-score for each data point. Recall that the z-score is given by:
# Z= (x − μ) / σ
z = centered / a.std()
z

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [18]:
# Exercises below are from https://gist.github.com/ryanorsinger/c4cf5a64ec33c014ff2e56951bc8a42d#file-numpy_exercises_part_1-py-L10
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)

In [20]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above listb
min_of_a = min(a)

In [21]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)

In [22]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = sum(a) / len(a)

In [23]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = 1
for number in a:
    product_of_a *= number

product_of_a

3628800

In [24]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [num**2 for num in a]
squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [25]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for num in a:
    if num % 2 != 0:
        odds_in_a.append(num)
odds_in_a

[1, 3, 5, 7, 9]

In [26]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for num in a:
    if num % 2 == 0:
        evens_in_a.append(num)
evens_in_a

[2, 4, 6, 8, 10]

In [27]:
a = np.array(a)
a[a % 2 == 0]

array([ 2,  4,  6,  8, 10])

In [28]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [29]:
b = np.array(b)
b.sum() # calling sum from the object (method)

33

In [30]:
np.sum(b) # calling sum from the class (function)

33

In [31]:
b.min()

3

In [32]:
b.max()

8

In [33]:
b.mean()

5.5

In [34]:
squares_of_b = b ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [35]:
odds_in_b = b[b % 2 != 0]
odds_in_b

array([3, 5, 7])

In [36]:
evens_in_b = b[b % 2 == 0]
evens_in_b

array([4, 6, 8])

In [37]:
print(b.shape)

(2, 3)


In [38]:
b.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [39]:
b.reshape(1, 6)

array([[3, 4, 5, 6, 7, 8]])

In [40]:
print(b.flatten())

[3 4 5 6 7 8]


In [41]:
print(b.reshape(6, 1))

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [42]:
# reshape by the 1 dimension of the array's length
b.reshape(-1)

array([3, 4, 5, 6, 7, 8])

In [43]:
b.reshape(6)

array([3, 4, 5, 6, 7, 8])

In [44]:
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [45]:
c = np.array(c)

In [46]:
print("min", c.min())
print("max", c.max())
print("sum", c.sum())
print("product", c.prod())

min 1
max 9
sum 45
product 362880


In [47]:
c.std()

2.581988897471611

In [48]:
variance = c.var()
variance

6.666666666666667

In [49]:
c.shape

(3, 3)

In [50]:
print(c.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [51]:
result = c * c.transpose()
result

array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [52]:
result.sum()

261

In [53]:
result.prod()

131681894400

In [54]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]


In [55]:
d = np.array(d)

In [56]:
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [57]:
np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [58]:
np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [59]:
d[d < 0]

array([-90, -30, -45, -45])

In [60]:
d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [64]:
np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [68]:
len(np.unique(d))

11

In [65]:
d.shape

(3, 6)

In [66]:
d.transpose().shape

(6, 3)

In [67]:
d.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [69]:
type(d)

numpy.ndarray

In [ ]:
def get_uniques(input):
    if type == numpy.ndarray:
        return np.unique(input)
    else:
        return None

In [ ]:
def get_positive_evens(input):
    evens = input[input % 2 == 0]
    positive_evens = evens[evens > 0]
    return positive_evens

In [70]:
d

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [71]:
for x in d:
    print(x)

[ 90  30  45   0 120 180]
[ 45 -90 -30 270  90   0]
[ 60  45 -45  90 -45 180]


In [75]:
result = d > 0

In [76]:
result

array([[ True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True, False],
       [ True,  True, False,  True, False,  True]])

In [90]:
len(result)
result.shape
result.size

18

In [78]:
number_of_trues = result.sum()
number_of_trues

12

In [91]:
number_of_falses = result.size - number_of_trues
number_of_falses

6

In [84]:
sum([True, False, True])

2

In [92]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [93]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])